# Generated by Django 3.2.4 on 2021-06-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Type', models.CharField(choices=[('regular', 'regular'), ('square', 'square')], max_length=100)),
                ('size', models.CharField(max_length=20)),
                ('toppings', models.CharField(max_length=400)),
            ],
        ),
    ]
